// Curated exercise seed data.
// Each entry maps to one row in the exercises table.
// Optional `aliases` array maps to rows in exercise_aliases.
//
// Fields required per entry:
//   canonicalName, displayName, normalizedCanonicalName,
//   category, movementPattern, primaryMuscleGroups, secondaryMuscleGroups,
//   equipmentType, trainingModes, repTrackingMode, isBilateral, isUnilateral,
//   difficultyLevel, reviewStatus, createdBySource
//
// Alias fields:
//   aliasText, normalizedAliasText, source, isPreferred

export const exercises: any[] = [
  // ─── CHEST ────────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Bench Press",
    displayName: "Barbell Bench Press",
    normalizedCanonicalName: "barbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Bench Press", normalizedAliasText: "bench press", source: "curated", isPreferred: true },
      { aliasText: "Flat Bench Press", normalizedAliasText: "flat bench press", source: "curated", isPreferred: false },
      { aliasText: "BB Bench Press", normalizedAliasText: "bb bench press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BACK ─────────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Bent-Over Row",
    displayName: "Barbell Bent-Over Row",
    normalizedCanonicalName: "barbell bent-over row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids", "middle trapezius"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "erector spinae"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Bent Over Row", normalizedAliasText: "bent over row", source: "curated", isPreferred: true },
      { aliasText: "BB Row", normalizedAliasText: "bb row", source: "curated", isPreferred: false },
      { aliasText: "Barbell Row", normalizedAliasText: "barbell row", source: "curated", isPreferred: false },
    ],
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Overhead Press",
    displayName: "Barbell Overhead Press",
    normalizedCanonicalName: "barbell overhead press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "upper trapezius", "core"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Overhead Press", normalizedAliasText: "overhead press", source: "curated", isPreferred: true },
      { aliasText: "Military Press", normalizedAliasText: "military press", source: "curated", isPreferred: false },
      { aliasText: "OHP", normalizedAliasText: "ohp", source: "curated", isPreferred: false },
    ],
  },

  // ─── BICEPS ───────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Curl",
    displayName: "Barbell Curl",
    normalizedCanonicalName: "barbell curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "BB Curl", normalizedAliasText: "bb curl", source: "curated", isPreferred: false },
      { aliasText: "Standing Barbell Curl", normalizedAliasText: "standing barbell curl", source: "curated", isPreferred: false },
      { aliasText: "Straight Bar Curl", normalizedAliasText: "straight bar curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Incline Barbell Bench Press",
    displayName: "Incline Barbell Bench Press",
    normalizedCanonicalName: "incline barbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major (upper)", "pectoralis minor"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Incline Bench Press", normalizedAliasText: "incline bench press", source: "curated", isPreferred: true },
      { aliasText: "Incline BB Press", normalizedAliasText: "incline bb press", source: "curated", isPreferred: false },
      { aliasText: "Incline Barbell Press", normalizedAliasText: "incline barbell press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Bench Press",
    displayName: "Dumbbell Bench Press",
    normalizedCanonicalName: "dumbbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Bench Press", normalizedAliasText: "db bench press", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Flat Press", normalizedAliasText: "dumbbell flat press", source: "curated", isPreferred: false },
      { aliasText: "Flat DB Press", normalizedAliasText: "flat db press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BACK ─────────────────────────────────────────────────────────────────

  {
    canonicalName: "Pull-Up",
    displayName: "Pull-Up",
    normalizedCanonicalName: "pull-up",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi"],
    secondaryMuscleGroups: ["biceps", "rhomboids", "rear deltoid", "core"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Pullup", normalizedAliasText: "pullup", source: "curated", isPreferred: false },
      { aliasText: "Overhand Pull-Up", normalizedAliasText: "overhand pull-up", source: "curated", isPreferred: false },
      { aliasText: "Weighted Pull-Up", normalizedAliasText: "weighted pull-up", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Lat Pulldown",
    displayName: "Lat Pulldown",
    normalizedCanonicalName: "lat pulldown",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "rhomboids"],
    equipmentType: "cable",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Lat Pulldown", normalizedAliasText: "cable lat pulldown", source: "curated", isPreferred: false },
      { aliasText: "Wide-Grip Lat Pulldown", normalizedAliasText: "wide-grip lat pulldown", source: "curated", isPreferred: false },
      { aliasText: "Pulldown", normalizedAliasText: "pulldown", source: "curated", isPreferred: false },
    ],
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────

  {
    canonicalName: "Dumbbell Shoulder Press",
    displayName: "Dumbbell Shoulder Press",
    normalizedCanonicalName: "dumbbell shoulder press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "upper trapezius"],
    equipmentType: "dumbbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Shoulder Press", normalizedAliasText: "db shoulder press", source: "curated", isPreferred: false },
      { aliasText: "Seated Dumbbell Press", normalizedAliasText: "seated dumbbell press", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell OHP", normalizedAliasText: "dumbbell ohp", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Arnold Press",
    displayName: "Arnold Press",
    normalizedCanonicalName: "arnold press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "rear deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Arnold Dumbbell Press", normalizedAliasText: "arnold dumbbell press", source: "curated", isPreferred: false },
      { aliasText: "Arnold DB Press", normalizedAliasText: "arnold db press", source: "curated", isPreferred: false },
      { aliasText: "Rotating Shoulder Press", normalizedAliasText: "rotating shoulder press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BICEPS ───────────────────────────────────────────────────────────────

  {
    canonicalName: "Dumbbell Bicep Curl",
    displayName: "Dumbbell Bicep Curl",
    normalizedCanonicalName: "dumbbell bicep curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Curl", normalizedAliasText: "db curl", source: "curated", isPreferred: true },
      { aliasText: "Dumbbell Curl", normalizedAliasText: "dumbbell curl", source: "curated", isPreferred: false },
      { aliasText: "Alternating Dumbbell Curl", normalizedAliasText: "alternating dumbbell curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Hammer Curl",
    displayName: "Hammer Curl",
    normalizedCanonicalName: "hammer curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["brachialis", "biceps brachii"],
    secondaryMuscleGroups: ["brachioradialis", "forearms"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Neutral Grip Curl", normalizedAliasText: "neutral grip curl", source: "curated", isPreferred: false },
      { aliasText: "DB Hammer Curl", normalizedAliasText: "db hammer curl", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Hammer Curl", normalizedAliasText: "dumbbell hammer curl", source: "curated", isPreferred: false },
    ],
  },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────

  {
    canonicalName: "Close-Grip Bench Press",
    displayName: "Close-Grip Bench Press",
    normalizedCanonicalName: "close-grip bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: ["pectoralis major", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "CGBP", normalizedAliasText: "cgbp", source: "curated", isPreferred: false },
      { aliasText: "Narrow Grip Bench Press", normalizedAliasText: "narrow grip bench press", source: "curated", isPreferred: false },
      { aliasText: "Close Grip Bench", normalizedAliasText: "close grip bench", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Barbell Skullcrusher",
    displayName: "Barbell Skullcrusher",
    normalizedCanonicalName: "barbell skullcrusher",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (long head)"],
    secondaryMuscleGroups: ["triceps brachii (lateral head)"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Skull Crusher", normalizedAliasText: "skull crusher", source: "curated", isPreferred: true },
      { aliasText: "Lying Triceps Extension", normalizedAliasText: "lying triceps extension", source: "curated", isPreferred: false },
      { aliasText: "Barbell Lying Triceps Extension", normalizedAliasText: "barbell lying triceps extension", source: "curated", isPreferred: false },
    ],
  },

  // ─── CHEST (continued) ────────────────────────────────────────────────────

  {
    canonicalName: "Decline Barbell Bench Press",
    displayName: "Decline Barbell Bench Press",
    normalizedCanonicalName: "decline barbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major (lower)"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Decline Bench Press", normalizedAliasText: "decline bench press", source: "curated", isPreferred: true },
      { aliasText: "Decline Press", normalizedAliasText: "decline press", source: "curated", isPreferred: false },
      { aliasText: "Decline BB Press", normalizedAliasText: "decline bb press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Chest Fly",
    displayName: "Cable Chest Fly",
    normalizedCanonicalName: "cable chest fly",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["anterior deltoid"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Fly", normalizedAliasText: "cable fly", source: "curated", isPreferred: true },
      { aliasText: "Cable Flye", normalizedAliasText: "cable flye", source: "curated", isPreferred: false },
      { aliasText: "Cable Chest Flye", normalizedAliasText: "cable chest flye", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Chest Fly",
    displayName: "Dumbbell Chest Fly",
    normalizedCanonicalName: "dumbbell chest fly",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["anterior deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Dumbbell Fly", normalizedAliasText: "dumbbell fly", source: "curated", isPreferred: true },
      { aliasText: "DB Fly", normalizedAliasText: "db fly", source: "curated", isPreferred: false },
      { aliasText: "DB Chest Fly", normalizedAliasText: "db chest fly", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Push-Up",
    displayName: "Push-Up",
    normalizedCanonicalName: "push-up",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid", "core"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Pushup", normalizedAliasText: "pushup", source: "curated", isPreferred: false },
      { aliasText: "Press-Up", normalizedAliasText: "press-up", source: "curated", isPreferred: false },
      { aliasText: "Standard Push-Up", normalizedAliasText: "standard push-up", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Machine Chest Press",
    displayName: "Machine Chest Press",
    normalizedCanonicalName: "machine chest press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "machine",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Chest Press Machine", normalizedAliasText: "chest press machine", source: "curated", isPreferred: false },
      { aliasText: "Machine Press", normalizedAliasText: "machine press", source: "curated", isPreferred: false },
      { aliasText: "Hammer Strength Chest Press", normalizedAliasText: "hammer strength chest press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BACK (continued) ─────────────────────────────────────────────────────

  {
    canonicalName: "Seated Cable Row",
    displayName: "Seated Cable Row",
    normalizedCanonicalName: "seated cable row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids", "middle trapezius"],
    secondaryMuscleGroups: ["biceps", "rear deltoid"],
    equipmentType: "cable",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Row", normalizedAliasText: "cable row", source: "curated", isPreferred: true },
      { aliasText: "Low Cable Row", normalizedAliasText: "low cable row", source: "curated", isPreferred: false },
      { aliasText: "Seated Row", normalizedAliasText: "seated row", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Single-Arm Row",
    displayName: "Dumbbell Single-Arm Row",
    normalizedCanonicalName: "dumbbell single-arm row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "core"],
    equipmentType: "dumbbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Single Arm Dumbbell Row", normalizedAliasText: "single arm dumbbell row", source: "curated", isPreferred: true },
      { aliasText: "One-Arm DB Row", normalizedAliasText: "one-arm db row", source: "curated", isPreferred: false },
      { aliasText: "DB Single Arm Row", normalizedAliasText: "db single arm row", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "T-Bar Row",
    displayName: "T-Bar Row",
    normalizedCanonicalName: "t-bar row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids", "middle trapezius"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "erector spinae"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "T Bar Row", normalizedAliasText: "t bar row", source: "curated", isPreferred: false },
      { aliasText: "Landmine Row", normalizedAliasText: "landmine row", source: "curated", isPreferred: false },
      { aliasText: "Chest-Supported T-Bar Row", normalizedAliasText: "chest-supported t-bar row", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Face Pull",
    displayName: "Cable Face Pull",
    normalizedCanonicalName: "cable face pull",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["posterior deltoid", "rhomboids"],
    secondaryMuscleGroups: ["middle trapezius", "rotator cuff"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Face Pull", normalizedAliasText: "face pull", source: "curated", isPreferred: true },
      { aliasText: "Rope Face Pull", normalizedAliasText: "rope face pull", source: "curated", isPreferred: false },
      { aliasText: "Cable Rear Delt Pull", normalizedAliasText: "cable rear delt pull", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Romanian Deadlift",
    displayName: "Romanian Deadlift",
    normalizedCanonicalName: "romanian deadlift",
    category: "strength",
    movementPattern: "hinge",
    primaryMuscleGroups: ["hamstrings", "gluteus maximus", "erector spinae"],
    secondaryMuscleGroups: ["latissimus dorsi", "upper back"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "RDL", normalizedAliasText: "rdl", source: "curated", isPreferred: true },
      { aliasText: "Barbell RDL", normalizedAliasText: "barbell rdl", source: "curated", isPreferred: false },
      { aliasText: "Straight-Leg Deadlift", normalizedAliasText: "straight-leg deadlift", source: "curated", isPreferred: false },
    ],
  },

  // ─── SHOULDERS (continued) ────────────────────────────────────────────────

  {
    canonicalName: "Dumbbell Lateral Raise",
    displayName: "Dumbbell Lateral Raise",
    normalizedCanonicalName: "dumbbell lateral raise",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["lateral deltoid"],
    secondaryMuscleGroups: ["anterior deltoid", "upper trapezius"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Lateral Raise", normalizedAliasText: "lateral raise", source: "curated", isPreferred: true },
      { aliasText: "Side Raise", normalizedAliasText: "side raise", source: "curated", isPreferred: false },
      { aliasText: "DB Lateral Raise", normalizedAliasText: "db lateral raise", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Front Raise",
    displayName: "Dumbbell Front Raise",
    normalizedCanonicalName: "dumbbell front raise",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid"],
    secondaryMuscleGroups: ["lateral deltoid", "pectoralis major (upper)"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Front Raise", normalizedAliasText: "front raise", source: "curated", isPreferred: true },
      { aliasText: "DB Front Raise", normalizedAliasText: "db front raise", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Anterior Raise", normalizedAliasText: "dumbbell anterior raise", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Rear Delt Dumbbell Fly",
    displayName: "Rear Delt Dumbbell Fly",
    normalizedCanonicalName: "rear delt dumbbell fly",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["posterior deltoid"],
    secondaryMuscleGroups: ["rhomboids", "middle trapezius"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Rear Delt Fly", normalizedAliasText: "rear delt fly", source: "curated", isPreferred: true },
      { aliasText: "Reverse Fly", normalizedAliasText: "reverse fly", source: "curated", isPreferred: false },
      { aliasText: "Bent-Over Rear Delt Fly", normalizedAliasText: "bent-over rear delt fly", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Lateral Raise",
    displayName: "Cable Lateral Raise",
    normalizedCanonicalName: "cable lateral raise",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["lateral deltoid"],
    secondaryMuscleGroups: ["anterior deltoid", "upper trapezius"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Side Raise", normalizedAliasText: "cable side raise", source: "curated", isPreferred: false },
      { aliasText: "Single-Arm Cable Lateral Raise", normalizedAliasText: "single-arm cable lateral raise", source: "curated", isPreferred: false },
      { aliasText: "Low Cable Lateral Raise", normalizedAliasText: "low cable lateral raise", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Barbell Upright Row",
    displayName: "Barbell Upright Row",
    normalizedCanonicalName: "barbell upright row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["lateral deltoid", "upper trapezius"],
    secondaryMuscleGroups: ["anterior deltoid", "biceps"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Upright Row", normalizedAliasText: "upright row", source: "curated", isPreferred: true },
      { aliasText: "BB Upright Row", normalizedAliasText: "bb upright row", source: "curated", isPreferred: false },
      { aliasText: "Barbell High Pull", normalizedAliasText: "barbell high pull", source: "curated", isPreferred: false },
    ],
  },

  // ─── BICEPS (continued) ───────────────────────────────────────────────────

  {
    canonicalName: "Incline Dumbbell Curl",
    displayName: "Incline Dumbbell Curl",
    normalizedCanonicalName: "incline dumbbell curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii (long head)"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Incline DB Curl", normalizedAliasText: "incline db curl", source: "curated", isPreferred: false },
      { aliasText: "Incline Bicep Curl", normalizedAliasText: "incline bicep curl", source: "curated", isPreferred: false },
      { aliasText: "Stretch Curl", normalizedAliasText: "stretch curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "EZ Bar Curl",
    displayName: "EZ Bar Curl",
    normalizedCanonicalName: "ez bar curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "brachioradialis", "forearms"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "EZ Curl", normalizedAliasText: "ez curl", source: "curated", isPreferred: true },
      { aliasText: "EZ Bar Bicep Curl", normalizedAliasText: "ez bar bicep curl", source: "curated", isPreferred: false },
      { aliasText: "W-Bar Curl", normalizedAliasText: "w-bar curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Barbell Preacher Curl",
    displayName: "Barbell Preacher Curl",
    normalizedCanonicalName: "barbell preacher curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii (short head)"],
    secondaryMuscleGroups: ["brachialis"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Preacher Curl", normalizedAliasText: "preacher curl", source: "curated", isPreferred: true },
      { aliasText: "Scott Curl", normalizedAliasText: "scott curl", source: "curated", isPreferred: false },
      { aliasText: "BB Preacher Curl", normalizedAliasText: "bb preacher curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Concentration Curl",
    displayName: "Concentration Curl",
    normalizedCanonicalName: "concentration curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Concentration Curl", normalizedAliasText: "db concentration curl", source: "curated", isPreferred: false },
      { aliasText: "Seated Concentration Curl", normalizedAliasText: "seated concentration curl", source: "curated", isPreferred: false },
      { aliasText: "Isolation Curl", normalizedAliasText: "isolation curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Straight Bar Curl",
    displayName: "Cable Straight Bar Curl",
    normalizedCanonicalName: "cable straight bar curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Curl", normalizedAliasText: "cable curl", source: "curated", isPreferred: true },
      { aliasText: "Low Cable Curl", normalizedAliasText: "low cable curl", source: "curated", isPreferred: false },
      { aliasText: "Cable Bar Curl", normalizedAliasText: "cable bar curl", source: "curated", isPreferred: false },
    ],
  },

  // ─── TRICEPS (continued) ──────────────────────────────────────────────────

  {
    canonicalName: "Triceps Dip",
    displayName: "Triceps Dip",
    normalizedCanonicalName: "triceps dip",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: ["anterior deltoid", "pectoralis major"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Tricep Dip", normalizedAliasText: "tricep dip", source: "curated", isPreferred: true },
      { aliasText: "Bench Dip", normalizedAliasText: "bench dip", source: "curated", isPreferred: false },
      { aliasText: "Chair Dip", normalizedAliasText: "chair dip", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Overhead Dumbbell Triceps Extension",
    displayName: "Overhead Dumbbell Triceps Extension",
    normalizedCanonicalName: "overhead dumbbell triceps extension",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (long head)"],
    secondaryMuscleGroups: ["triceps brachii (lateral head)"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Overhead Triceps Extension", normalizedAliasText: "overhead triceps extension", source: "curated", isPreferred: true },
      { aliasText: "French Press", normalizedAliasText: "french press", source: "curated", isPreferred: false },
      { aliasText: "DB Overhead Extension", normalizedAliasText: "db overhead extension", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Triceps Kickback",
    displayName: "Dumbbell Triceps Kickback",
    normalizedCanonicalName: "dumbbell triceps kickback",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (lateral head)"],
    secondaryMuscleGroups: ["triceps brachii (long head)"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Tricep Kickback", normalizedAliasText: "tricep kickback", source: "curated", isPreferred: true },
      { aliasText: "DB Kickback", normalizedAliasText: "db kickback", source: "curated", isPreferred: false },
      { aliasText: "Bent-Over Kickback", normalizedAliasText: "bent-over kickback", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Diamond Push-Up",
    displayName: "Diamond Push-Up",
    normalizedCanonicalName: "diamond push-up",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: ["pectoralis major", "anterior deltoid"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Diamond Pushup", normalizedAliasText: "diamond pushup", source: "curated", isPreferred: false },
      { aliasText: "Triangle Push-Up", normalizedAliasText: "triangle push-up", source: "curated", isPreferred: false },
      { aliasText: "Close-Grip Push-Up", normalizedAliasText: "close-grip push-up", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Bar Triceps Pushdown",
    displayName: "Cable Bar Triceps Pushdown",
    normalizedCanonicalName: "cable bar triceps pushdown",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: [],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Tricep Pushdown", normalizedAliasText: "tricep pushdown", source: "curated", isPreferred: true },
      { aliasText: "Cable Tricep Pressdown", normalizedAliasText: "cable tricep pressdown", source: "curated", isPreferred: false },
      { aliasText: "Straight Bar Pushdown", normalizedAliasText: "straight bar pushdown", source: "curated", isPreferred: false },
    ],
  },

  // ─── CHEST (continued) ────────────────────────────────────────────────────

  {
    canonicalName: "Pec Deck Machine",
    displayName: "Pec Deck Machine",
    normalizedCanonicalName: "pec deck machine",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["anterior deltoid"],
    equipmentType: "machine",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Pec Deck", normalizedAliasText: "pec deck", source: "curated", isPreferred: true },
      { aliasText: "Butterfly Machine", normalizedAliasText: "butterfly machine", source: "curated", isPreferred: false },
      { aliasText: "Machine Chest Fly", normalizedAliasText: "machine chest fly", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Pullover",
    displayName: "Dumbbell Pullover",
    normalizedCanonicalName: "dumbbell pullover",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["pectoralis major", "latissimus dorsi"],
    secondaryMuscleGroups: ["triceps", "serratus anterior"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Pullover", normalizedAliasText: "db pullover", source: "curated", isPreferred: false },
      { aliasText: "Chest Pullover", normalizedAliasText: "chest pullover", source: "curated", isPreferred: false },
      { aliasText: "Straight-Arm Pullover", normalizedAliasText: "straight-arm pullover", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Incline Dumbbell Press",
    displayName: "Incline Dumbbell Press",
    normalizedCanonicalName: "incline dumbbell press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major (upper)"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Incline DB Press", normalizedAliasText: "incline db press", source: "curated", isPreferred: false },
      { aliasText: "Incline Dumbbell Chest Press", normalizedAliasText: "incline dumbbell chest press", source: "curated", isPreferred: false },
      { aliasText: "Incline DB Bench Press", normalizedAliasText: "incline db bench press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Crossover",
    displayName: "Cable Crossover",
    normalizedCanonicalName: "cable crossover",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["anterior deltoid"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "High Cable Crossover", normalizedAliasText: "high cable crossover", source: "curated", isPreferred: false },
      { aliasText: "Cross Cable Fly", normalizedAliasText: "cross cable fly", source: "curated", isPreferred: false },
      { aliasText: "Cable Cross", normalizedAliasText: "cable cross", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Chest Dip",
    displayName: "Chest Dip",
    normalizedCanonicalName: "chest dip",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major (lower)"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Parallel Bar Dip", normalizedAliasText: "parallel bar dip", source: "curated", isPreferred: false },
      { aliasText: "Weighted Dip", normalizedAliasText: "weighted dip", source: "curated", isPreferred: false },
      { aliasText: "Dip", normalizedAliasText: "dip", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Barbell Floor Press",
    displayName: "Barbell Floor Press",
    normalizedCanonicalName: "barbell floor press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Floor Press", normalizedAliasText: "floor press", source: "curated", isPreferred: true },
      { aliasText: "BB Floor Press", normalizedAliasText: "bb floor press", source: "curated", isPreferred: false },
      { aliasText: "Flat Floor Press", normalizedAliasText: "flat floor press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Landmine Press",
    displayName: "Landmine Press",
    normalizedCanonicalName: "landmine press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major (upper)", "anterior deltoid"],
    secondaryMuscleGroups: ["triceps", "core"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Single-Arm Landmine Press", normalizedAliasText: "single-arm landmine press", source: "curated", isPreferred: false },
      { aliasText: "Landmine Chest Press", normalizedAliasText: "landmine chest press", source: "curated", isPreferred: false },
      { aliasText: "Angled Barbell Press", normalizedAliasText: "angled barbell press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Incline Push-Up",
    displayName: "Incline Push-Up",
    normalizedCanonicalName: "incline push-up",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major (lower)"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "bodyweight",
    trainingModes: ["strength"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Incline Pushup", normalizedAliasText: "incline pushup", source: "curated", isPreferred: false },
      { aliasText: "Elevated Push-Up", normalizedAliasText: "elevated push-up", source: "curated", isPreferred: false },
      { aliasText: "Box Push-Up", normalizedAliasText: "box push-up", source: "curated", isPreferred: false },
    ],
  },

  // ─── BACK (continued) ─────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Deadlift",
    displayName: "Barbell Deadlift",
    normalizedCanonicalName: "barbell deadlift",
    category: "strength",
    movementPattern: "hinge",
    primaryMuscleGroups: ["erector spinae", "gluteus maximus", "hamstrings"],
    secondaryMuscleGroups: ["latissimus dorsi", "trapezius", "quadriceps", "forearms"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Deadlift", normalizedAliasText: "deadlift", source: "curated", isPreferred: true },
      { aliasText: "Conventional Deadlift", normalizedAliasText: "conventional deadlift", source: "curated", isPreferred: false },
      { aliasText: "BB Deadlift", normalizedAliasText: "bb deadlift", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Chin-Up",
    displayName: "Chin-Up",
    normalizedCanonicalName: "chin-up",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii", "latissimus dorsi"],
    secondaryMuscleGroups: ["brachialis", "rhomboids", "core"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Chinup", normalizedAliasText: "chinup", source: "curated", isPreferred: false },
      { aliasText: "Underhand Pull-Up", normalizedAliasText: "underhand pull-up", source: "curated", isPreferred: false },
      { aliasText: "Supinated Pull-Up", normalizedAliasText: "supinated pull-up", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Straight-Arm Pulldown",
    displayName: "Straight-Arm Pulldown",
    normalizedCanonicalName: "straight-arm pulldown",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi"],
    secondaryMuscleGroups: ["teres major", "posterior deltoid"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Straight Arm Lat Pulldown", normalizedAliasText: "straight arm lat pulldown", source: "curated", isPreferred: false },
      { aliasText: "Cable Straight Arm Pulldown", normalizedAliasText: "cable straight arm pulldown", source: "curated", isPreferred: false },
      { aliasText: "Overhead Pulldown", normalizedAliasText: "overhead pulldown", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Inverted Row",
    displayName: "Inverted Row",
    normalizedCanonicalName: "inverted row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids", "middle trapezius"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "core"],
    equipmentType: "bodyweight",
    trainingModes: ["strength"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Body Row", normalizedAliasText: "body row", source: "curated", isPreferred: false },
      { aliasText: "Horizontal Pull-Up", normalizedAliasText: "horizontal pull-up", source: "curated", isPreferred: false },
      { aliasText: "Australian Pull-Up", normalizedAliasText: "australian pull-up", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Barbell Shrug",
    displayName: "Barbell Shrug",
    normalizedCanonicalName: "barbell shrug",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["upper trapezius"],
    secondaryMuscleGroups: ["levator scapulae", "rhomboids"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Shrug", normalizedAliasText: "shrug", source: "curated", isPreferred: false },
      { aliasText: "BB Shrug", normalizedAliasText: "bb shrug", source: "curated", isPreferred: false },
      { aliasText: "Barbell Shoulder Shrug", normalizedAliasText: "barbell shoulder shrug", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Rack Pull",
    displayName: "Rack Pull",
    normalizedCanonicalName: "rack pull",
    category: "strength",
    movementPattern: "hinge",
    primaryMuscleGroups: ["erector spinae", "trapezius", "gluteus maximus"],
    secondaryMuscleGroups: ["latissimus dorsi", "rhomboids", "forearms"],
    equipmentType: "barbell",
    trainingModes: ["strength"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Partial Deadlift", normalizedAliasText: "partial deadlift", source: "curated", isPreferred: false },
      { aliasText: "Block Pull", normalizedAliasText: "block pull", source: "curated", isPreferred: false },
      { aliasText: "Pin Pull", normalizedAliasText: "pin pull", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Machine Seated Row",
    displayName: "Machine Seated Row",
    normalizedCanonicalName: "machine seated row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids"],
    secondaryMuscleGroups: ["biceps", "rear deltoid"],
    equipmentType: "machine",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Machine Row", normalizedAliasText: "machine row", source: "curated", isPreferred: true },
      { aliasText: "Hammer Strength Row", normalizedAliasText: "hammer strength row", source: "curated", isPreferred: false },
      { aliasText: "Plate-Loaded Row Machine", normalizedAliasText: "plate-loaded row machine", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Meadows Row",
    displayName: "Meadows Row",
    normalizedCanonicalName: "meadows row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "teres major"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "core"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "advanced",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Landmine Single Arm Row", normalizedAliasText: "landmine single arm row", source: "curated", isPreferred: false },
      { aliasText: "One-Arm T-Bar Row", normalizedAliasText: "one-arm t-bar row", source: "curated", isPreferred: false },
      { aliasText: "Meadow Row", normalizedAliasText: "meadow row", source: "curated", isPreferred: false },
    ],
  },

  // ─── SHOULDERS (continued) ────────────────────────────────────────────────

  {
    canonicalName: "Machine Shoulder Press",
    displayName: "Machine Shoulder Press",
    normalizedCanonicalName: "machine shoulder press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps"],
    equipmentType: "machine",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Shoulder Press Machine", normalizedAliasText: "shoulder press machine", source: "curated", isPreferred: false },
      { aliasText: "Seated Machine Press", normalizedAliasText: "seated machine press", source: "curated", isPreferred: false },
      { aliasText: "Hammer Strength Shoulder Press", normalizedAliasText: "hammer strength shoulder press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Push Press",
    displayName: "Push Press",
    normalizedCanonicalName: "push press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "quadriceps", "gluteus maximus", "core"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Barbell Push Press", normalizedAliasText: "barbell push press", source: "curated", isPreferred: false },
      { aliasText: "Dynamic Overhead Press", normalizedAliasText: "dynamic overhead press", source: "curated", isPreferred: false },
      { aliasText: "Hip-Drive Press", normalizedAliasText: "hip-drive press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Front Raise",
    displayName: "Cable Front Raise",
    normalizedCanonicalName: "cable front raise",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid"],
    secondaryMuscleGroups: ["lateral deltoid", "pectoralis major (upper)"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Anterior Raise", normalizedAliasText: "cable anterior raise", source: "curated", isPreferred: false },
      { aliasText: "Low Cable Front Raise", normalizedAliasText: "low cable front raise", source: "curated", isPreferred: false },
      { aliasText: "Cable Shoulder Front Raise", normalizedAliasText: "cable shoulder front raise", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Kettlebell Press",
    displayName: "Kettlebell Press",
    normalizedCanonicalName: "kettlebell press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "core"],
    equipmentType: "kettlebell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "KB Press", normalizedAliasText: "kb press", source: "curated", isPreferred: false },
      { aliasText: "Kettlebell Shoulder Press", normalizedAliasText: "kettlebell shoulder press", source: "curated", isPreferred: false },
      { aliasText: "Single-Arm Kettlebell Press", normalizedAliasText: "single-arm kettlebell press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Bent-Over Lateral Raise",
    displayName: "Dumbbell Bent-Over Lateral Raise",
    normalizedCanonicalName: "dumbbell bent-over lateral raise",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["posterior deltoid"],
    secondaryMuscleGroups: ["rhomboids", "middle trapezius", "lateral deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Bent-Over Lateral Raise", normalizedAliasText: "bent-over lateral raise", source: "curated", isPreferred: true },
      { aliasText: "DB Rear Delt Raise", normalizedAliasText: "db rear delt raise", source: "curated", isPreferred: false },
      { aliasText: "Prone Lateral Raise", normalizedAliasText: "prone lateral raise", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Landmine Lateral Raise",
    displayName: "Landmine Lateral Raise",
    normalizedCanonicalName: "landmine lateral raise",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["lateral deltoid"],
    secondaryMuscleGroups: ["anterior deltoid", "upper trapezius"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Landmine Side Raise", normalizedAliasText: "landmine side raise", source: "curated", isPreferred: false },
      { aliasText: "Plate Lateral Raise", normalizedAliasText: "plate lateral raise", source: "curated", isPreferred: false },
      { aliasText: "Viking Press Lateral", normalizedAliasText: "viking press lateral", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Upright Row",
    displayName: "Cable Upright Row",
    normalizedCanonicalName: "cable upright row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["lateral deltoid", "upper trapezius"],
    secondaryMuscleGroups: ["anterior deltoid", "biceps"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable High Pull", normalizedAliasText: "cable high pull", source: "curated", isPreferred: false },
      { aliasText: "Low Cable Upright Row", normalizedAliasText: "low cable upright row", source: "curated", isPreferred: false },
      { aliasText: "Straight Bar Cable Upright Row", normalizedAliasText: "straight bar cable upright row", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Rear Delt Fly",
    displayName: "Cable Rear Delt Fly",
    normalizedCanonicalName: "cable rear delt fly",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["posterior deltoid"],
    secondaryMuscleGroups: ["rhomboids", "middle trapezius"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Reverse Fly", normalizedAliasText: "cable reverse fly", source: "curated", isPreferred: false },
      { aliasText: "Cable Bent-Over Rear Delt Fly", normalizedAliasText: "cable bent-over rear delt fly", source: "curated", isPreferred: false },
      { aliasText: "Cable Rear Delt Raise", normalizedAliasText: "cable rear delt raise", source: "curated", isPreferred: false },
    ],
  },

  // ─── BICEPS (continued) ───────────────────────────────────────────────────

  {
    canonicalName: "Dumbbell Preacher Curl",
    displayName: "Dumbbell Preacher Curl",
    normalizedCanonicalName: "dumbbell preacher curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii (short head)"],
    secondaryMuscleGroups: ["brachialis"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Preacher Curl", normalizedAliasText: "db preacher curl", source: "curated", isPreferred: false },
      { aliasText: "One-Arm Preacher Curl", normalizedAliasText: "one-arm preacher curl", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Scott Curl", normalizedAliasText: "dumbbell scott curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Spider Curl",
    displayName: "Spider Curl",
    normalizedCanonicalName: "spider curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Prone Incline Curl", normalizedAliasText: "prone incline curl", source: "curated", isPreferred: false },
      { aliasText: "Lying Incline Curl", normalizedAliasText: "lying incline curl", source: "curated", isPreferred: false },
      { aliasText: "Barbell Spider Curl", normalizedAliasText: "barbell spider curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Zottman Curl",
    displayName: "Zottman Curl",
    normalizedCanonicalName: "zottman curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii", "brachioradialis"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Zottman Curl", normalizedAliasText: "db zottman curl", source: "curated", isPreferred: false },
      { aliasText: "Supinating Reverse Curl", normalizedAliasText: "supinating reverse curl", source: "curated", isPreferred: false },
      { aliasText: "Pronation Curl", normalizedAliasText: "pronation curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Rope Hammer Curl",
    displayName: "Cable Rope Hammer Curl",
    normalizedCanonicalName: "cable rope hammer curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["brachialis", "biceps brachii"],
    secondaryMuscleGroups: ["brachioradialis", "forearms"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Rope Hammer Curl", normalizedAliasText: "rope hammer curl", source: "curated", isPreferred: true },
      { aliasText: "Cable Hammer Curl", normalizedAliasText: "cable hammer curl", source: "curated", isPreferred: false },
      { aliasText: "Neutral Grip Cable Curl", normalizedAliasText: "neutral grip cable curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Machine Bicep Curl",
    displayName: "Machine Bicep Curl",
    normalizedCanonicalName: "machine bicep curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis"],
    equipmentType: "machine",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Machine Curl", normalizedAliasText: "machine curl", source: "curated", isPreferred: true },
      { aliasText: "Curl Machine", normalizedAliasText: "curl machine", source: "curated", isPreferred: false },
      { aliasText: "Seated Machine Curl", normalizedAliasText: "seated machine curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cross-Body Hammer Curl",
    displayName: "Cross-Body Hammer Curl",
    normalizedCanonicalName: "cross-body hammer curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["brachialis", "biceps brachii"],
    secondaryMuscleGroups: ["brachioradialis"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Across Body Hammer Curl", normalizedAliasText: "across body hammer curl", source: "curated", isPreferred: false },
      { aliasText: "Cross Hammer Curl", normalizedAliasText: "cross hammer curl", source: "curated", isPreferred: false },
      { aliasText: "DB Cross-Body Curl", normalizedAliasText: "db cross-body curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Reverse Barbell Curl",
    displayName: "Reverse Barbell Curl",
    normalizedCanonicalName: "reverse barbell curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["brachioradialis", "biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Reverse Curl", normalizedAliasText: "reverse curl", source: "curated", isPreferred: true },
      { aliasText: "Overhand Curl", normalizedAliasText: "overhand curl", source: "curated", isPreferred: false },
      { aliasText: "Pronated Barbell Curl", normalizedAliasText: "pronated barbell curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable EZ Bar Curl",
    displayName: "Cable EZ Bar Curl",
    normalizedCanonicalName: "cable ez bar curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "EZ Bar Cable Curl", normalizedAliasText: "ez bar cable curl", source: "curated", isPreferred: false },
      { aliasText: "Low Pulley EZ Bar Curl", normalizedAliasText: "low pulley ez bar curl", source: "curated", isPreferred: false },
      { aliasText: "Cable W-Bar Curl", normalizedAliasText: "cable w-bar curl", source: "curated", isPreferred: false },
    ],
  },

  // ─── TRICEPS (continued) ──────────────────────────────────────────────────

  {
    canonicalName: "Overhead Cable Triceps Extension",
    displayName: "Overhead Cable Triceps Extension",
    normalizedCanonicalName: "overhead cable triceps extension",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (long head)"],
    secondaryMuscleGroups: ["triceps brachii (lateral head)"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Overhead Extension", normalizedAliasText: "cable overhead extension", source: "curated", isPreferred: true },
      { aliasText: "High Cable Triceps Extension", normalizedAliasText: "high cable triceps extension", source: "curated", isPreferred: false },
      { aliasText: "Rope Overhead Extension", normalizedAliasText: "rope overhead extension", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Skullcrusher",
    displayName: "Dumbbell Skullcrusher",
    normalizedCanonicalName: "dumbbell skullcrusher",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (long head)"],
    secondaryMuscleGroups: ["triceps brachii (lateral head)"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Skull Crusher", normalizedAliasText: "db skull crusher", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Lying Triceps Extension", normalizedAliasText: "dumbbell lying triceps extension", source: "curated", isPreferred: false },
      { aliasText: "DB Skullcrusher", normalizedAliasText: "db skullcrusher", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Triceps Kickback",
    displayName: "Cable Triceps Kickback",
    normalizedCanonicalName: "cable triceps kickback",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (lateral head)"],
    secondaryMuscleGroups: ["triceps brachii (long head)"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Kickback", normalizedAliasText: "cable kickback", source: "curated", isPreferred: true },
      { aliasText: "Single Arm Cable Kickback", normalizedAliasText: "single arm cable kickback", source: "curated", isPreferred: false },
      { aliasText: "Cable Tricep Kickback", normalizedAliasText: "cable tricep kickback", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Tate Press",
    displayName: "Tate Press",
    normalizedCanonicalName: "tate press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: ["anterior deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Tate Press", normalizedAliasText: "db tate press", source: "curated", isPreferred: false },
      { aliasText: "Elbows-Out Triceps Extension", normalizedAliasText: "elbows-out triceps extension", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Tate Press", normalizedAliasText: "dumbbell tate press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "JM Press",
    displayName: "JM Press",
    normalizedCanonicalName: "jm press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: ["anterior deltoid", "pectoralis major"],
    equipmentType: "barbell",
    trainingModes: ["strength"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "advanced",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "JM Barbell Press", normalizedAliasText: "jm barbell press", source: "curated", isPreferred: false },
      { aliasText: "JM Triceps Press", normalizedAliasText: "jm triceps press", source: "curated", isPreferred: false },
      { aliasText: "Hybrid Skull Crusher Press", normalizedAliasText: "hybrid skull crusher press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Machine Triceps Extension",
    displayName: "Machine Triceps Extension",
    normalizedCanonicalName: "machine triceps extension",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: [],
    equipmentType: "machine",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Machine Tricep Extension", normalizedAliasText: "machine tricep extension", source: "curated", isPreferred: true },
      { aliasText: "Triceps Extension Machine", normalizedAliasText: "triceps extension machine", source: "curated", isPreferred: false },
      { aliasText: "Seated Machine Triceps Extension", normalizedAliasText: "seated machine triceps extension", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "One-Arm Overhead Cable Extension",
    displayName: "One-Arm Overhead Cable Extension",
    normalizedCanonicalName: "one-arm overhead cable extension",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (long head)"],
    secondaryMuscleGroups: ["triceps brachii (lateral head)"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Single Arm Overhead Tricep Extension", normalizedAliasText: "single arm overhead tricep extension", source: "curated", isPreferred: true },
      { aliasText: "Unilateral Cable Overhead Extension", normalizedAliasText: "unilateral cable overhead extension", source: "curated", isPreferred: false },
      { aliasText: "One Arm Cable Overhead Extension", normalizedAliasText: "one arm cable overhead extension", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Reverse-Grip Triceps Pushdown",
    displayName: "Reverse-Grip Triceps Pushdown",
    normalizedCanonicalName: "reverse-grip triceps pushdown",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (medial head)"],
    secondaryMuscleGroups: ["triceps brachii (lateral head)"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Reverse Grip Pushdown", normalizedAliasText: "reverse grip pushdown", source: "curated", isPreferred: true },
      { aliasText: "Underhand Triceps Pushdown", normalizedAliasText: "underhand triceps pushdown", source: "curated", isPreferred: false },
      { aliasText: "Reverse Cable Pushdown", normalizedAliasText: "reverse cable pushdown", source: "curated", isPreferred: false },
    ],
  },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────

  {
    canonicalName: "Cable Rope Triceps Pushdown",
    displayName: "Cable Rope Triceps Pushdown",
    normalizedCanonicalName: "cable rope triceps pushdown",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: [],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Rope Pushdown", normalizedAliasText: "rope pushdown", source: "curated", isPreferred: true },
      { aliasText: "Tricep Rope Pushdown", normalizedAliasText: "tricep rope pushdown", source: "curated", isPreferred: false },
      { aliasText: "Cable Rope Pressdown", normalizedAliasText: "cable rope pressdown", source: "curated", isPreferred: false },
    ],
  },
];
