// Curated exercise seed data.
// Each entry maps to one row in the exercises table.
// Optional `aliases` array maps to rows in exercise_aliases.
//
// Fields required per entry:
//   canonicalName, displayName, normalizedCanonicalName,
//   category, movementPattern, primaryMuscleGroups, secondaryMuscleGroups,
//   equipmentType, trainingModes, repTrackingMode, isBilateral, isUnilateral,
//   difficultyLevel, reviewStatus, createdBySource
//
// Alias fields:
//   aliasText, normalizedAliasText, source, isPreferred

export const exercises: any[] = [
  // ─── CHEST ────────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Bench Press",
    displayName: "Barbell Bench Press",
    normalizedCanonicalName: "barbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Bench Press", normalizedAliasText: "bench press", source: "curated", isPreferred: true },
      { aliasText: "Flat Bench Press", normalizedAliasText: "flat bench press", source: "curated", isPreferred: false },
      { aliasText: "BB Bench Press", normalizedAliasText: "bb bench press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BACK ─────────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Bent-Over Row",
    displayName: "Barbell Bent-Over Row",
    normalizedCanonicalName: "barbell bent-over row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids", "middle trapezius"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "erector spinae"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Bent Over Row", normalizedAliasText: "bent over row", source: "curated", isPreferred: true },
      { aliasText: "BB Row", normalizedAliasText: "bb row", source: "curated", isPreferred: false },
      { aliasText: "Barbell Row", normalizedAliasText: "barbell row", source: "curated", isPreferred: false },
    ],
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Overhead Press",
    displayName: "Barbell Overhead Press",
    normalizedCanonicalName: "barbell overhead press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "upper trapezius", "core"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Overhead Press", normalizedAliasText: "overhead press", source: "curated", isPreferred: true },
      { aliasText: "Military Press", normalizedAliasText: "military press", source: "curated", isPreferred: false },
      { aliasText: "OHP", normalizedAliasText: "ohp", source: "curated", isPreferred: false },
    ],
  },

  // ─── BICEPS ───────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Curl",
    displayName: "Barbell Curl",
    normalizedCanonicalName: "barbell curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "BB Curl", normalizedAliasText: "bb curl", source: "curated", isPreferred: false },
      { aliasText: "Standing Barbell Curl", normalizedAliasText: "standing barbell curl", source: "curated", isPreferred: false },
      { aliasText: "Straight Bar Curl", normalizedAliasText: "straight bar curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Incline Barbell Bench Press",
    displayName: "Incline Barbell Bench Press",
    normalizedCanonicalName: "incline barbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major (upper)", "pectoralis minor"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Incline Bench Press", normalizedAliasText: "incline bench press", source: "curated", isPreferred: true },
      { aliasText: "Incline BB Press", normalizedAliasText: "incline bb press", source: "curated", isPreferred: false },
      { aliasText: "Incline Barbell Press", normalizedAliasText: "incline barbell press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Bench Press",
    displayName: "Dumbbell Bench Press",
    normalizedCanonicalName: "dumbbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Bench Press", normalizedAliasText: "db bench press", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Flat Press", normalizedAliasText: "dumbbell flat press", source: "curated", isPreferred: false },
      { aliasText: "Flat DB Press", normalizedAliasText: "flat db press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BACK ─────────────────────────────────────────────────────────────────

  {
    canonicalName: "Pull-Up",
    displayName: "Pull-Up",
    normalizedCanonicalName: "pull-up",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi"],
    secondaryMuscleGroups: ["biceps", "rhomboids", "rear deltoid", "core"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Pullup", normalizedAliasText: "pullup", source: "curated", isPreferred: false },
      { aliasText: "Overhand Pull-Up", normalizedAliasText: "overhand pull-up", source: "curated", isPreferred: false },
      { aliasText: "Weighted Pull-Up", normalizedAliasText: "weighted pull-up", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Lat Pulldown",
    displayName: "Lat Pulldown",
    normalizedCanonicalName: "lat pulldown",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "rhomboids"],
    equipmentType: "cable",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Lat Pulldown", normalizedAliasText: "cable lat pulldown", source: "curated", isPreferred: false },
      { aliasText: "Wide-Grip Lat Pulldown", normalizedAliasText: "wide-grip lat pulldown", source: "curated", isPreferred: false },
      { aliasText: "Pulldown", normalizedAliasText: "pulldown", source: "curated", isPreferred: false },
    ],
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────

  {
    canonicalName: "Dumbbell Shoulder Press",
    displayName: "Dumbbell Shoulder Press",
    normalizedCanonicalName: "dumbbell shoulder press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "upper trapezius"],
    equipmentType: "dumbbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Shoulder Press", normalizedAliasText: "db shoulder press", source: "curated", isPreferred: false },
      { aliasText: "Seated Dumbbell Press", normalizedAliasText: "seated dumbbell press", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell OHP", normalizedAliasText: "dumbbell ohp", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Arnold Press",
    displayName: "Arnold Press",
    normalizedCanonicalName: "arnold press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "rear deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Arnold Dumbbell Press", normalizedAliasText: "arnold dumbbell press", source: "curated", isPreferred: false },
      { aliasText: "Arnold DB Press", normalizedAliasText: "arnold db press", source: "curated", isPreferred: false },
      { aliasText: "Rotating Shoulder Press", normalizedAliasText: "rotating shoulder press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BICEPS ───────────────────────────────────────────────────────────────

  {
    canonicalName: "Dumbbell Bicep Curl",
    displayName: "Dumbbell Bicep Curl",
    normalizedCanonicalName: "dumbbell bicep curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Curl", normalizedAliasText: "db curl", source: "curated", isPreferred: true },
      { aliasText: "Dumbbell Curl", normalizedAliasText: "dumbbell curl", source: "curated", isPreferred: false },
      { aliasText: "Alternating Dumbbell Curl", normalizedAliasText: "alternating dumbbell curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Hammer Curl",
    displayName: "Hammer Curl",
    normalizedCanonicalName: "hammer curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["brachialis", "biceps brachii"],
    secondaryMuscleGroups: ["brachioradialis", "forearms"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Neutral Grip Curl", normalizedAliasText: "neutral grip curl", source: "curated", isPreferred: false },
      { aliasText: "DB Hammer Curl", normalizedAliasText: "db hammer curl", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Hammer Curl", normalizedAliasText: "dumbbell hammer curl", source: "curated", isPreferred: false },
    ],
  },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────

  {
    canonicalName: "Close-Grip Bench Press",
    displayName: "Close-Grip Bench Press",
    normalizedCanonicalName: "close-grip bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: ["pectoralis major", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "CGBP", normalizedAliasText: "cgbp", source: "curated", isPreferred: false },
      { aliasText: "Narrow Grip Bench Press", normalizedAliasText: "narrow grip bench press", source: "curated", isPreferred: false },
      { aliasText: "Close Grip Bench", normalizedAliasText: "close grip bench", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Barbell Skullcrusher",
    displayName: "Barbell Skullcrusher",
    normalizedCanonicalName: "barbell skullcrusher",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (long head)"],
    secondaryMuscleGroups: ["triceps brachii (lateral head)"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Skull Crusher", normalizedAliasText: "skull crusher", source: "curated", isPreferred: true },
      { aliasText: "Lying Triceps Extension", normalizedAliasText: "lying triceps extension", source: "curated", isPreferred: false },
      { aliasText: "Barbell Lying Triceps Extension", normalizedAliasText: "barbell lying triceps extension", source: "curated", isPreferred: false },
    ],
  },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────

  {
    canonicalName: "Cable Rope Triceps Pushdown",
    displayName: "Cable Rope Triceps Pushdown",
    normalizedCanonicalName: "cable rope triceps pushdown",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: [],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Rope Pushdown", normalizedAliasText: "rope pushdown", source: "curated", isPreferred: true },
      { aliasText: "Tricep Rope Pushdown", normalizedAliasText: "tricep rope pushdown", source: "curated", isPreferred: false },
      { aliasText: "Cable Rope Pressdown", normalizedAliasText: "cable rope pressdown", source: "curated", isPreferred: false },
    ],
  },
];
