// Curated exercise seed data.
// Each entry maps to one row in the exercises table.
// Optional `aliases` array maps to rows in exercise_aliases.
//
// Fields required per entry:
//   canonicalName, displayName, normalizedCanonicalName,
//   category, movementPattern, primaryMuscleGroups, secondaryMuscleGroups,
//   equipmentType, trainingModes, repTrackingMode, isBilateral, isUnilateral,
//   difficultyLevel, reviewStatus, createdBySource
//
// Alias fields:
//   aliasText, normalizedAliasText, source, isPreferred

export const exercises: any[] = [
  // ─── CHEST ────────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Bench Press",
    displayName: "Barbell Bench Press",
    normalizedCanonicalName: "barbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Bench Press", normalizedAliasText: "bench press", source: "curated", isPreferred: true },
      { aliasText: "Flat Bench Press", normalizedAliasText: "flat bench press", source: "curated", isPreferred: false },
      { aliasText: "BB Bench Press", normalizedAliasText: "bb bench press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BACK ─────────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Bent-Over Row",
    displayName: "Barbell Bent-Over Row",
    normalizedCanonicalName: "barbell bent-over row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids", "middle trapezius"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "erector spinae"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Bent Over Row", normalizedAliasText: "bent over row", source: "curated", isPreferred: true },
      { aliasText: "BB Row", normalizedAliasText: "bb row", source: "curated", isPreferred: false },
      { aliasText: "Barbell Row", normalizedAliasText: "barbell row", source: "curated", isPreferred: false },
    ],
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Overhead Press",
    displayName: "Barbell Overhead Press",
    normalizedCanonicalName: "barbell overhead press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "upper trapezius", "core"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Overhead Press", normalizedAliasText: "overhead press", source: "curated", isPreferred: true },
      { aliasText: "Military Press", normalizedAliasText: "military press", source: "curated", isPreferred: false },
      { aliasText: "OHP", normalizedAliasText: "ohp", source: "curated", isPreferred: false },
    ],
  },

  // ─── BICEPS ───────────────────────────────────────────────────────────────

  {
    canonicalName: "Barbell Curl",
    displayName: "Barbell Curl",
    normalizedCanonicalName: "barbell curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "BB Curl", normalizedAliasText: "bb curl", source: "curated", isPreferred: false },
      { aliasText: "Standing Barbell Curl", normalizedAliasText: "standing barbell curl", source: "curated", isPreferred: false },
      { aliasText: "Straight Bar Curl", normalizedAliasText: "straight bar curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Incline Barbell Bench Press",
    displayName: "Incline Barbell Bench Press",
    normalizedCanonicalName: "incline barbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major (upper)", "pectoralis minor"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Incline Bench Press", normalizedAliasText: "incline bench press", source: "curated", isPreferred: true },
      { aliasText: "Incline BB Press", normalizedAliasText: "incline bb press", source: "curated", isPreferred: false },
      { aliasText: "Incline Barbell Press", normalizedAliasText: "incline barbell press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Bench Press",
    displayName: "Dumbbell Bench Press",
    normalizedCanonicalName: "dumbbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Bench Press", normalizedAliasText: "db bench press", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Flat Press", normalizedAliasText: "dumbbell flat press", source: "curated", isPreferred: false },
      { aliasText: "Flat DB Press", normalizedAliasText: "flat db press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BACK ─────────────────────────────────────────────────────────────────

  {
    canonicalName: "Pull-Up",
    displayName: "Pull-Up",
    normalizedCanonicalName: "pull-up",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi"],
    secondaryMuscleGroups: ["biceps", "rhomboids", "rear deltoid", "core"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Pullup", normalizedAliasText: "pullup", source: "curated", isPreferred: false },
      { aliasText: "Overhand Pull-Up", normalizedAliasText: "overhand pull-up", source: "curated", isPreferred: false },
      { aliasText: "Weighted Pull-Up", normalizedAliasText: "weighted pull-up", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Lat Pulldown",
    displayName: "Lat Pulldown",
    normalizedCanonicalName: "lat pulldown",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "rhomboids"],
    equipmentType: "cable",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Lat Pulldown", normalizedAliasText: "cable lat pulldown", source: "curated", isPreferred: false },
      { aliasText: "Wide-Grip Lat Pulldown", normalizedAliasText: "wide-grip lat pulldown", source: "curated", isPreferred: false },
      { aliasText: "Pulldown", normalizedAliasText: "pulldown", source: "curated", isPreferred: false },
    ],
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────

  {
    canonicalName: "Dumbbell Shoulder Press",
    displayName: "Dumbbell Shoulder Press",
    normalizedCanonicalName: "dumbbell shoulder press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "upper trapezius"],
    equipmentType: "dumbbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Shoulder Press", normalizedAliasText: "db shoulder press", source: "curated", isPreferred: false },
      { aliasText: "Seated Dumbbell Press", normalizedAliasText: "seated dumbbell press", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell OHP", normalizedAliasText: "dumbbell ohp", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Arnold Press",
    displayName: "Arnold Press",
    normalizedCanonicalName: "arnold press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscleGroups: ["triceps", "rear deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Arnold Dumbbell Press", normalizedAliasText: "arnold dumbbell press", source: "curated", isPreferred: false },
      { aliasText: "Arnold DB Press", normalizedAliasText: "arnold db press", source: "curated", isPreferred: false },
      { aliasText: "Rotating Shoulder Press", normalizedAliasText: "rotating shoulder press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BICEPS ───────────────────────────────────────────────────────────────

  {
    canonicalName: "Dumbbell Bicep Curl",
    displayName: "Dumbbell Bicep Curl",
    normalizedCanonicalName: "dumbbell bicep curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Curl", normalizedAliasText: "db curl", source: "curated", isPreferred: true },
      { aliasText: "Dumbbell Curl", normalizedAliasText: "dumbbell curl", source: "curated", isPreferred: false },
      { aliasText: "Alternating Dumbbell Curl", normalizedAliasText: "alternating dumbbell curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Hammer Curl",
    displayName: "Hammer Curl",
    normalizedCanonicalName: "hammer curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["brachialis", "biceps brachii"],
    secondaryMuscleGroups: ["brachioradialis", "forearms"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Neutral Grip Curl", normalizedAliasText: "neutral grip curl", source: "curated", isPreferred: false },
      { aliasText: "DB Hammer Curl", normalizedAliasText: "db hammer curl", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Hammer Curl", normalizedAliasText: "dumbbell hammer curl", source: "curated", isPreferred: false },
    ],
  },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────

  {
    canonicalName: "Close-Grip Bench Press",
    displayName: "Close-Grip Bench Press",
    normalizedCanonicalName: "close-grip bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: ["pectoralis major", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "CGBP", normalizedAliasText: "cgbp", source: "curated", isPreferred: false },
      { aliasText: "Narrow Grip Bench Press", normalizedAliasText: "narrow grip bench press", source: "curated", isPreferred: false },
      { aliasText: "Close Grip Bench", normalizedAliasText: "close grip bench", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Barbell Skullcrusher",
    displayName: "Barbell Skullcrusher",
    normalizedCanonicalName: "barbell skullcrusher",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (long head)"],
    secondaryMuscleGroups: ["triceps brachii (lateral head)"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Skull Crusher", normalizedAliasText: "skull crusher", source: "curated", isPreferred: true },
      { aliasText: "Lying Triceps Extension", normalizedAliasText: "lying triceps extension", source: "curated", isPreferred: false },
      { aliasText: "Barbell Lying Triceps Extension", normalizedAliasText: "barbell lying triceps extension", source: "curated", isPreferred: false },
    ],
  },

  // ─── CHEST (continued) ────────────────────────────────────────────────────

  {
    canonicalName: "Decline Barbell Bench Press",
    displayName: "Decline Barbell Bench Press",
    normalizedCanonicalName: "decline barbell bench press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major (lower)"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Decline Bench Press", normalizedAliasText: "decline bench press", source: "curated", isPreferred: true },
      { aliasText: "Decline Press", normalizedAliasText: "decline press", source: "curated", isPreferred: false },
      { aliasText: "Decline BB Press", normalizedAliasText: "decline bb press", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Chest Fly",
    displayName: "Cable Chest Fly",
    normalizedCanonicalName: "cable chest fly",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["anterior deltoid"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Fly", normalizedAliasText: "cable fly", source: "curated", isPreferred: true },
      { aliasText: "Cable Flye", normalizedAliasText: "cable flye", source: "curated", isPreferred: false },
      { aliasText: "Cable Chest Flye", normalizedAliasText: "cable chest flye", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Chest Fly",
    displayName: "Dumbbell Chest Fly",
    normalizedCanonicalName: "dumbbell chest fly",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["anterior deltoid"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Dumbbell Fly", normalizedAliasText: "dumbbell fly", source: "curated", isPreferred: true },
      { aliasText: "DB Fly", normalizedAliasText: "db fly", source: "curated", isPreferred: false },
      { aliasText: "DB Chest Fly", normalizedAliasText: "db chest fly", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Push-Up",
    displayName: "Push-Up",
    normalizedCanonicalName: "push-up",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid", "core"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Pushup", normalizedAliasText: "pushup", source: "curated", isPreferred: false },
      { aliasText: "Press-Up", normalizedAliasText: "press-up", source: "curated", isPreferred: false },
      { aliasText: "Standard Push-Up", normalizedAliasText: "standard push-up", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Machine Chest Press",
    displayName: "Machine Chest Press",
    normalizedCanonicalName: "machine chest press",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["pectoralis major"],
    secondaryMuscleGroups: ["triceps", "anterior deltoid"],
    equipmentType: "machine",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Chest Press Machine", normalizedAliasText: "chest press machine", source: "curated", isPreferred: false },
      { aliasText: "Machine Press", normalizedAliasText: "machine press", source: "curated", isPreferred: false },
      { aliasText: "Hammer Strength Chest Press", normalizedAliasText: "hammer strength chest press", source: "curated", isPreferred: false },
    ],
  },

  // ─── BACK (continued) ─────────────────────────────────────────────────────

  {
    canonicalName: "Seated Cable Row",
    displayName: "Seated Cable Row",
    normalizedCanonicalName: "seated cable row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids", "middle trapezius"],
    secondaryMuscleGroups: ["biceps", "rear deltoid"],
    equipmentType: "cable",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Row", normalizedAliasText: "cable row", source: "curated", isPreferred: true },
      { aliasText: "Low Cable Row", normalizedAliasText: "low cable row", source: "curated", isPreferred: false },
      { aliasText: "Seated Row", normalizedAliasText: "seated row", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Single-Arm Row",
    displayName: "Dumbbell Single-Arm Row",
    normalizedCanonicalName: "dumbbell single-arm row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "core"],
    equipmentType: "dumbbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Single Arm Dumbbell Row", normalizedAliasText: "single arm dumbbell row", source: "curated", isPreferred: true },
      { aliasText: "One-Arm DB Row", normalizedAliasText: "one-arm db row", source: "curated", isPreferred: false },
      { aliasText: "DB Single Arm Row", normalizedAliasText: "db single arm row", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "T-Bar Row",
    displayName: "T-Bar Row",
    normalizedCanonicalName: "t-bar row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["latissimus dorsi", "rhomboids", "middle trapezius"],
    secondaryMuscleGroups: ["biceps", "rear deltoid", "erector spinae"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "T Bar Row", normalizedAliasText: "t bar row", source: "curated", isPreferred: false },
      { aliasText: "Landmine Row", normalizedAliasText: "landmine row", source: "curated", isPreferred: false },
      { aliasText: "Chest-Supported T-Bar Row", normalizedAliasText: "chest-supported t-bar row", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Face Pull",
    displayName: "Cable Face Pull",
    normalizedCanonicalName: "cable face pull",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["posterior deltoid", "rhomboids"],
    secondaryMuscleGroups: ["middle trapezius", "rotator cuff"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Face Pull", normalizedAliasText: "face pull", source: "curated", isPreferred: true },
      { aliasText: "Rope Face Pull", normalizedAliasText: "rope face pull", source: "curated", isPreferred: false },
      { aliasText: "Cable Rear Delt Pull", normalizedAliasText: "cable rear delt pull", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Romanian Deadlift",
    displayName: "Romanian Deadlift",
    normalizedCanonicalName: "romanian deadlift",
    category: "strength",
    movementPattern: "hinge",
    primaryMuscleGroups: ["hamstrings", "gluteus maximus", "erector spinae"],
    secondaryMuscleGroups: ["latissimus dorsi", "upper back"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "RDL", normalizedAliasText: "rdl", source: "curated", isPreferred: true },
      { aliasText: "Barbell RDL", normalizedAliasText: "barbell rdl", source: "curated", isPreferred: false },
      { aliasText: "Straight-Leg Deadlift", normalizedAliasText: "straight-leg deadlift", source: "curated", isPreferred: false },
    ],
  },

  // ─── SHOULDERS (continued) ────────────────────────────────────────────────

  {
    canonicalName: "Dumbbell Lateral Raise",
    displayName: "Dumbbell Lateral Raise",
    normalizedCanonicalName: "dumbbell lateral raise",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["lateral deltoid"],
    secondaryMuscleGroups: ["anterior deltoid", "upper trapezius"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Lateral Raise", normalizedAliasText: "lateral raise", source: "curated", isPreferred: true },
      { aliasText: "Side Raise", normalizedAliasText: "side raise", source: "curated", isPreferred: false },
      { aliasText: "DB Lateral Raise", normalizedAliasText: "db lateral raise", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Front Raise",
    displayName: "Dumbbell Front Raise",
    normalizedCanonicalName: "dumbbell front raise",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["anterior deltoid"],
    secondaryMuscleGroups: ["lateral deltoid", "pectoralis major (upper)"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Front Raise", normalizedAliasText: "front raise", source: "curated", isPreferred: true },
      { aliasText: "DB Front Raise", normalizedAliasText: "db front raise", source: "curated", isPreferred: false },
      { aliasText: "Dumbbell Anterior Raise", normalizedAliasText: "dumbbell anterior raise", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Rear Delt Dumbbell Fly",
    displayName: "Rear Delt Dumbbell Fly",
    normalizedCanonicalName: "rear delt dumbbell fly",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["posterior deltoid"],
    secondaryMuscleGroups: ["rhomboids", "middle trapezius"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Rear Delt Fly", normalizedAliasText: "rear delt fly", source: "curated", isPreferred: true },
      { aliasText: "Reverse Fly", normalizedAliasText: "reverse fly", source: "curated", isPreferred: false },
      { aliasText: "Bent-Over Rear Delt Fly", normalizedAliasText: "bent-over rear delt fly", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Lateral Raise",
    displayName: "Cable Lateral Raise",
    normalizedCanonicalName: "cable lateral raise",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["lateral deltoid"],
    secondaryMuscleGroups: ["anterior deltoid", "upper trapezius"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Side Raise", normalizedAliasText: "cable side raise", source: "curated", isPreferred: false },
      { aliasText: "Single-Arm Cable Lateral Raise", normalizedAliasText: "single-arm cable lateral raise", source: "curated", isPreferred: false },
      { aliasText: "Low Cable Lateral Raise", normalizedAliasText: "low cable lateral raise", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Barbell Upright Row",
    displayName: "Barbell Upright Row",
    normalizedCanonicalName: "barbell upright row",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["lateral deltoid", "upper trapezius"],
    secondaryMuscleGroups: ["anterior deltoid", "biceps"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Upright Row", normalizedAliasText: "upright row", source: "curated", isPreferred: true },
      { aliasText: "BB Upright Row", normalizedAliasText: "bb upright row", source: "curated", isPreferred: false },
      { aliasText: "Barbell High Pull", normalizedAliasText: "barbell high pull", source: "curated", isPreferred: false },
    ],
  },

  // ─── BICEPS (continued) ───────────────────────────────────────────────────

  {
    canonicalName: "Incline Dumbbell Curl",
    displayName: "Incline Dumbbell Curl",
    normalizedCanonicalName: "incline dumbbell curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii (long head)"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Incline DB Curl", normalizedAliasText: "incline db curl", source: "curated", isPreferred: false },
      { aliasText: "Incline Bicep Curl", normalizedAliasText: "incline bicep curl", source: "curated", isPreferred: false },
      { aliasText: "Stretch Curl", normalizedAliasText: "stretch curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "EZ Bar Curl",
    displayName: "EZ Bar Curl",
    normalizedCanonicalName: "ez bar curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "brachioradialis", "forearms"],
    equipmentType: "barbell",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "EZ Curl", normalizedAliasText: "ez curl", source: "curated", isPreferred: true },
      { aliasText: "EZ Bar Bicep Curl", normalizedAliasText: "ez bar bicep curl", source: "curated", isPreferred: false },
      { aliasText: "W-Bar Curl", normalizedAliasText: "w-bar curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Barbell Preacher Curl",
    displayName: "Barbell Preacher Curl",
    normalizedCanonicalName: "barbell preacher curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii (short head)"],
    secondaryMuscleGroups: ["brachialis"],
    equipmentType: "barbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Preacher Curl", normalizedAliasText: "preacher curl", source: "curated", isPreferred: true },
      { aliasText: "Scott Curl", normalizedAliasText: "scott curl", source: "curated", isPreferred: false },
      { aliasText: "BB Preacher Curl", normalizedAliasText: "bb preacher curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Concentration Curl",
    displayName: "Concentration Curl",
    normalizedCanonicalName: "concentration curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "DB Concentration Curl", normalizedAliasText: "db concentration curl", source: "curated", isPreferred: false },
      { aliasText: "Seated Concentration Curl", normalizedAliasText: "seated concentration curl", source: "curated", isPreferred: false },
      { aliasText: "Isolation Curl", normalizedAliasText: "isolation curl", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Straight Bar Curl",
    displayName: "Cable Straight Bar Curl",
    normalizedCanonicalName: "cable straight bar curl",
    category: "strength",
    movementPattern: "pull",
    primaryMuscleGroups: ["biceps brachii"],
    secondaryMuscleGroups: ["brachialis", "forearms"],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Cable Curl", normalizedAliasText: "cable curl", source: "curated", isPreferred: true },
      { aliasText: "Low Cable Curl", normalizedAliasText: "low cable curl", source: "curated", isPreferred: false },
      { aliasText: "Cable Bar Curl", normalizedAliasText: "cable bar curl", source: "curated", isPreferred: false },
    ],
  },

  // ─── TRICEPS (continued) ──────────────────────────────────────────────────

  {
    canonicalName: "Triceps Dip",
    displayName: "Triceps Dip",
    normalizedCanonicalName: "triceps dip",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: ["anterior deltoid", "pectoralis major"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Tricep Dip", normalizedAliasText: "tricep dip", source: "curated", isPreferred: true },
      { aliasText: "Bench Dip", normalizedAliasText: "bench dip", source: "curated", isPreferred: false },
      { aliasText: "Chair Dip", normalizedAliasText: "chair dip", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Overhead Dumbbell Triceps Extension",
    displayName: "Overhead Dumbbell Triceps Extension",
    normalizedCanonicalName: "overhead dumbbell triceps extension",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (long head)"],
    secondaryMuscleGroups: ["triceps brachii (lateral head)"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Overhead Triceps Extension", normalizedAliasText: "overhead triceps extension", source: "curated", isPreferred: true },
      { aliasText: "French Press", normalizedAliasText: "french press", source: "curated", isPreferred: false },
      { aliasText: "DB Overhead Extension", normalizedAliasText: "db overhead extension", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Dumbbell Triceps Kickback",
    displayName: "Dumbbell Triceps Kickback",
    normalizedCanonicalName: "dumbbell triceps kickback",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii (lateral head)"],
    secondaryMuscleGroups: ["triceps brachii (long head)"],
    equipmentType: "dumbbell",
    trainingModes: ["hypertrophy"],
    isBilateral: false,
    isUnilateral: true,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Tricep Kickback", normalizedAliasText: "tricep kickback", source: "curated", isPreferred: true },
      { aliasText: "DB Kickback", normalizedAliasText: "db kickback", source: "curated", isPreferred: false },
      { aliasText: "Bent-Over Kickback", normalizedAliasText: "bent-over kickback", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Diamond Push-Up",
    displayName: "Diamond Push-Up",
    normalizedCanonicalName: "diamond push-up",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: ["pectoralis major", "anterior deltoid"],
    equipmentType: "bodyweight",
    trainingModes: ["strength", "hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "intermediate",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Diamond Pushup", normalizedAliasText: "diamond pushup", source: "curated", isPreferred: false },
      { aliasText: "Triangle Push-Up", normalizedAliasText: "triangle push-up", source: "curated", isPreferred: false },
      { aliasText: "Close-Grip Push-Up", normalizedAliasText: "close-grip push-up", source: "curated", isPreferred: false },
    ],
  },

  {
    canonicalName: "Cable Bar Triceps Pushdown",
    displayName: "Cable Bar Triceps Pushdown",
    normalizedCanonicalName: "cable bar triceps pushdown",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: [],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Tricep Pushdown", normalizedAliasText: "tricep pushdown", source: "curated", isPreferred: true },
      { aliasText: "Cable Tricep Pressdown", normalizedAliasText: "cable tricep pressdown", source: "curated", isPreferred: false },
      { aliasText: "Straight Bar Pushdown", normalizedAliasText: "straight bar pushdown", source: "curated", isPreferred: false },
    ],
  },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────

  {
    canonicalName: "Cable Rope Triceps Pushdown",
    displayName: "Cable Rope Triceps Pushdown",
    normalizedCanonicalName: "cable rope triceps pushdown",
    category: "strength",
    movementPattern: "push",
    primaryMuscleGroups: ["triceps brachii"],
    secondaryMuscleGroups: [],
    equipmentType: "cable",
    trainingModes: ["hypertrophy"],
    isBilateral: true,
    isUnilateral: false,
    repTrackingMode: "reps",
    difficultyLevel: "beginner",
    createdBySource: "curated",
    reviewStatus: "approved",
    aliases: [
      { aliasText: "Rope Pushdown", normalizedAliasText: "rope pushdown", source: "curated", isPreferred: true },
      { aliasText: "Tricep Rope Pushdown", normalizedAliasText: "tricep rope pushdown", source: "curated", isPreferred: false },
      { aliasText: "Cable Rope Pressdown", normalizedAliasText: "cable rope pressdown", source: "curated", isPreferred: false },
    ],
  },
];
